//
// This file is part of an OMNeT++/OMNEST simulation example.
//
// Copyright (C) 2009 OpenSim Ltd., Rudolf Hornig
//
// This file is distributed WITHOUT ANY WARRANTY. See the file
// `license' for details on this and other legal matters.
//

//
// @titlepage
//
// <center><h1>An AGDX switch and End System implementation</h1></center>
//
//

package afdx;

// C++ classes are in the 'afdx' namespace
@namespace(afdx);

// this sample simulation is part of OMNeT++
@license(omnetpp);
